version: "3.9"

services:
  pdf-toolbox:
    image: jojomak/pdf-toolbox:latest
    container_name: pdf-toolbox
    volumes:
      - ./.env:/app/.env
    environment:
      - APP_NAME=PDF-Toolbox
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - OUTPUT_FILE_NAME=out.pdf
    ports:
      - "8080:8080"
    restart: unless-stopped
