name: build-pdf-toolbox

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -o dist/pdf-toolbox-linux-amd64 .
        GOOS=darwin GOARCH=amd64 go build -o dist/pdf-toolbox-mac-amd64 .
        GOOS=windows GOARCH=amd64 go build -o dist/pdf-toolbox-win-amd64.exe .

    - name: Test
      run: go test -v ./...

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pdf-toolbox
        path: dist/
        retention-days: 5

  push-to-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/pdf-toolbox
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
