name: build-pdf-toolbox

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -o dist/pdf-toolbox-linux-amd64 .
        GOOS=darwin GOARCH=amd64 go build -o dist/pdf-toolbox-mac-amd64 .
        GOOS=windows GOARCH=amd64 go build -o dist/pdf-toolbox-win-amd64.exe .

    - name: Test
      run: go test -v ./...

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pdf-toolbox
        path: dist/
        retention-days: 5
