name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: pdf-toolbox
          path: dist

      - name: Generate changelog
        run: |
          # Get the previous tag, if it exists
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            # If no previous tag exists, get all commits
            git log --pretty=format:"* %s" > CHANGELOG.md
          else
            # Get commits since the last tag
            git log ${PREV_TAG}..HEAD --pretty=format:"* %s" > CHANGELOG.md
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            dist/pdf-toolbox-linux-amd64
            dist/pdf-toolbox-mac-amd64
            dist/pdf-toolbox-win-amd64.exe
          draft: false
          prerelease: false
